"""V1_init

Revision ID: 16053698f3bb
Revises: 
Create Date: 2026-06-16 02:15:51.424495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16053698f3bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('macro_f1', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['model_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('predicted_group_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('xai_hotspots', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['predicted_group_id'], ['drug_groups.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('model_metrics')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
